import type { Metadata } from "next";
import { Koulen, Funnel_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"


const koulen = Koulen({
  variable: "--font-koulen",
  weight: "400",
  subsets: ["latin"],
});

const funnelSans = Funnel_Sans({
  variable: "--font-funnel-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${koulen.variable} ${funnelSans.variable} h-full antialiased`}
    >
      <body className="min-h-full h-screen w-screen flex flex-col justify-between items-center gap-2 p-2">
        <Header />
        <div className="h-full w-full border-3 border-accent overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
