export const invoices = [
  {
    id: "INV1",
    status: true,
    dateCreated: "2026-06-01",
    dateDue: "2026-06-15",
    customerId: "CUST-901",
    GSTpercent: 10,
    discountPercent: 0,
    paidAmount: 2500,
    items: [
      {
        description: "Frontend Development",
        hours: 5,
        rate: 500,
        amount: 2500,
      },
    ],
  },
  {
    id: "INV2",
    status: false,
    dateCreated: "2026-06-05",
    dateDue: "2026-06-20",
    customerId: "CUST-902",
    GSTpercent: 18,
    discountPercent: 5,
    paidAmount: 1000,
    items: [
      {
        description: "UI/UX Design Wireframes",
        hours: 10,
        rate: 300,
        amount: 3000,
      },
      {
        description: "Logo Design",
        hours: 2,
        rate: 400,
        amount: 800,
      },
    ],
  },
  {
    id: "INV3",
    status: false,
    dateCreated: "2026-06-10",
    dateDue: "2026-06-25",
    customerId: "CUST-903",
    GSTpercent: 5,
    discountPercent: 10,
    paidAmount: 0,
    items: [
      {
        description: "SEO Consulting",
        hours: 8,
        rate: 250,
        amount: 2000,
      },
    ],
  },
  {
    id: "INV4",
    status: true,
    dateCreated: "2026-06-12",
    dateDue: "2026-06-27",
    customerId: "CUST-901",
    GSTpercent: 12,
    discountPercent: 0,
    paidAmount: 1500,
    items: [
      {
        description: "Server Maintenance",
        hours: 3,
        rate: 500,
        amount: 1500,
      },
    ],
  },
  {
    id: "INV5",
    status: false,
    dateCreated: "2026-06-15",
    dateDue: "2026-06-30",
    customerId: "CUST-904",
    GSTpercent: 18,
    discountPercent: 15,
    paidAmount: 5000,
    items: [
      {
        description: "Mobile App Development",
        hours: 20,
        rate: 600,
        amount: 12000,
      },
      {
        description: "API Integration",
        hours: 5,
        rate: 600,
        amount: 3000,
      },
    ],
  },
];